### ISSUE TITLE
 Fatal error: Cannot declare class Swift, because the name is already in use in D:\xampp\htdocs\vendor\swiftmailer\swiftmailer\lib\classes\Swift.php on line 17

### ISSUE THREAD

**Issue by mohananagavenkat** [swiftmailer/swiftmailer#1012]
Fatal error: Cannot declare class Swift, because the name is already in use in D:\xampp\htdocs\vendor\swiftmailer\swiftmailer\lib\classes\Swift.php on line 17

**Comment by magicbel** [comment]
same here

**Comment by FerRguez94** [comment]
same here

**Comment by halfer** [comment]
@mohananagavenkat @magicbel @FerRguez94 I don't think that's enough information to debug your issue. Have you a minimal working script that illustrates this problem?

**Comment by Zanark** [comment]
`<?php


require_once 'swiftmailer/lib/swift_required.php';
require_once 'swiftmailer/vendor/autoload.php';

//echo "inside emailer";

$transport = (new Swift_SmtpTransport('smtp.gmail.com', 25))
  ->setUsername('****')
  ->setPassword('****')
  ;

$mailer = new Swift_Mailer($transport);

// Create a message
$message = (new Swift_Message('This email is sent using Swift Mailer'))
  ->setFrom(['****' => '****'])
  ->setTo(['***' => '****'])
  ->setBody('The Body.')
  ;

// Send the message
$result = $mailer->send($message);
?>`

I still get the error 

Fatal error: Cannot declare class Swift, because the name is already in use in C:\xampp\htdocs\ldynamic\Internship\project3381\test\swiftmailer\lib\classes\Swift.php on line 16

The Swift.php file mentioned here is the same one in the repository.

**Comment by Zanark** [comment]
SOLUTION : We do not need to include swift_required.php 

and

` $transport = (new Swift_SmtpTransport('smtp.gmail.com', 465 , 'ssl')) `

**Comment by mohananagavenkat** [comment]
@Zanark even though it is out of issue I want to ask you another question. Did swiftmailer worked properly with gmail smtp server..? I tried previously by using my gmail credentials but I ended up with some fatal error. I googled and found that you have to allow less secure apps . I changed those settings also. But I still got error. Now I am using some 3rd party API to send  emails. If you have a solution to make GMAIL work properly , please post it here

**Comment by Zanark** [comment]
It is working well for me. The script I uploaded above is the one I'm using right now.
Just apply the changes that I included in the solution.

**Comment by mohananagavenkat** [comment]
Yeah they are correct ! Ok .. I will try again and will update :+1:

**Comment by fabpot** [comment]
Closing as there is no more activities.
