### ISSUE TITLE
SMTP mail silently fails after some time from a configuration change.

### ISSUE THREAD

**Issue by tmoravec** [swiftmailer/swiftmailer#1026]
Sending email is unreliable from Grav CMS, which uses Symfony and Swiftmailer. After I do a change in settings, emails get sent for about two hours. Later it silently fails, with no errors in the error log.

This happens on Bluehost, so there could be some issues with the provider. Their only support was "our server is working correctly, contact the developer."

The SMTP settings are correct (should be sending through SMTP).

Any ideas how to debug this further?

Thanks for any pointers.

| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | Symfony
| Swiftmailer version | 5.4.8
| PHP version         | 7.0

### Observed behaviour
Email doesn't get sent after two hours after a configuration change.

### Expected behaviour
All calls to send email should work.

**Comment by tomzx** [comment]
Is the SMTP server local to the machine or remote? Do you happen to have full access to the machine or is this a very constrained shared environment?

If it is using the SMTP server local to the machine, I'd check that sent mails get logged in /var/log/mail.log. If you have enough rights, you could set a cron job that runs every 5 minutes and sends an email to one of your address, so that you can track how long it takes before it fails. If you can't, then you can write a simple script that does the same thing and use an external service that will call this script/page every 5 minutes. By the way, how did you determine it was after two hours?

AFAIK, Grav CMS does not come with the email feature by default, it comes from a plugin (https://github.com/getgrav/grav-plugin-email). I'd probably look for help there.

**Comment by fabpot** [comment]
Closing as there is no more feedback from the reporter.
