### ISSUE TITLE
Brackets in SetFrom are missing

### ISSUE THREAD

**Issue by cech12** [swiftmailer/swiftmailer#1033]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | in Yii 2
| Swiftmailer version | 5.4.3
| PHP version         | 7.1.1

### Observed behaviour
`$mailer->setFrom(["name@mail.com" => "Name (Something in Brackets) xxx"])`
generates this header information:
`From: Name (Something in Brackets) xxx <name@mail.com>`
But the received mail has this header information:
```
From: Name  
xxx <name@mail.com>
```
The brackets are replaced with a line break.

### Expected behaviour
The received message should have this header information:
`From: Name (Something in Brackets) xxx <name@mail.com>`
or
`From: "Name (Something in Brackets) xxx" <name@mail.com>`

### Example
```
Yii::$app->mailer->setTextBody("This is a test mail.")
  ->setFrom(["name@mail.com" => "Name (Something in Brackets) xxx"])
  ->setTo("receiver@mail.com")
  ->setSubject('test mail')
  ->setHtmlBody('<b>This is a test mail.</b>')
  ->send();
```

**Comment by Rotzbua** [comment]
@cech12 Please add which transport you used. (Maybe the brackets filtered for security reasons.)

**Comment by cech12** [comment]
@Rotzbua Sorry, but I don't know, what you mean with "transport". :/

I tested the normal php mail function on 2 different web servers
```
mail("receiver@mail.com", "test mail", "This is a test mail.", "From: Name (Something in Brackets) xxx <name@mail.com>");
```
and the result is the same. 

The received message had this header information:
```
From: Name  
xxx <name@mail.com>
```

Maybe there are some security mechanisms. How can I test it?

**Comment by Rotzbua** [comment]
I asked for the sending method: mail(), sendmail or smtp. Swiftm. calls them Swift_SmtpTransport, Swift_SendmailTransport, Swift_MailTransport.

I suggest your swiftmailer use phps `mail()`, because it shows the same behaviour. `mail()` is just a proxy function in php. It is processed very different on different computer systems. That's the reason why `Swift_MailTransport` is removed in v6.

Try smtp?

By the way: I tested your code on my webspace (php7.0) and the brackets are not removed. Seems that my provider has a different setup than your provider.

**Comment by cech12** [comment]
Ah okay! Yes I use the mail transport `Swift_MailTransport`. 

If this function is removed in the new swiftmailer version, in the future nobody will have this problem. I reached that I wanted to reach. :D 

I will try the SMTP mail transport and if there is a Problem I will open a new Issue.
So this Issue can be closed. :)

Thanks for your help! :)
