### ISSUE TITLE
Use without composer

### ISSUE THREAD

**Issue by jbringolf** [swiftmailer/swiftmailer#1070]
| Q                   | No
| ------------------- | -----
| Bug report?         |no
| Feature request?    | no
| RFC?                | no
| How used?           | Standalone
| Swiftmailer version | 6
| PHP version         | 7.0.28

Sorry, not sure how to use this template. 

Trying to find out if anyone has a guide to using Swiftmailer if the system you are working on is at an ISP that does not allow composer usage? Found a list of validator files to incllude but it appears there may be other packages missing. Does anyone have a list of required support packages? Hate to go back to Version 5, but may be my only alternative at this point.

Thank you

### Observed behaviour

Errors on loading.

**Comment by tomzx** [comment]
Not allowed to use `composer` in what way? In the worse case, you can simply package all the dependencies `composer` would fetch (the `vendor` directory) and have that on your server, no need to use `composer.phar`.

**Comment by raphievila** [comment]
Interested to know how to do this as well. I use SwiftMailer since when was a Perl extension, now upgrading, do not work unless under Composer. I have a whole library developed through out 10 years, and right now I don't have time to upgrade every single object with all the JSONs and other files required to work with Composer. The mail class I created using SwiftMailer now is broken, because even though I required the `vendor/swiftmailer/swiftmailer/lib/swift_required.php` I get an error since the class can't find any of the classes to this library...

`Fatal error: Class 'System\Communications\Swift_SmtpTransport' not found in C:\library\System\Communications\mail.php on line 174`

This is how the code is called inside private method:

```
require 'Apps/vendor/swiftmailer/swiftmailer/lib/swift_required.php';
 $transport = (new Swift_SmtpTransport('smtp.server.fake', 587))
 ->setUserName($user)
 ->setPassword($pass)
 ->setEncryption('tls');
 $mailer = Swift_Mailer::newInstance($transport);
```

I have a custom `autoload` that I use on my code, and the Composer `autoload` is not intuitive as the one  used on our system, as I said, for over 10 years. It would take me about 6 to 12 month to make each of the proprietary classes to work with composer and that's not acceptable since I need to fix this issue now.

As you can see, the error is that the class where SwiftMailer is being requested, is trying to find the class under System\Communications namespace. Because composer let you create a fake namespace structure, there is not consistent structure or pattern, there is not quick way to develop an auto loader, that can process the vast diversity of developers ideas that do not conflict with an already established one, which might take a couple of hours or days. From a business stand point that's a lot of hours ($$$$$).

So for young systems that has not many Classes or Objects, upgrading the process to use Composer is a no brainier, but for more complicated systems, just changing to a Composer methodology is not as simple as it sounds. I will probably do it eventually, but is a long process, and what you are only one man team, is a very long process.

But, after so much talk. The point is, that is always good to have documentation how to implement SwiftMailer for systems that do not uses Composer as a framework and already have a custom framework developed. Where the `require` method made sense using the Perl which was not intrusive as Composer is. You either use Composer way or the highway.

I'm not complaining about this, and probably I look for other solutions, probably writing my own, using the traditional mail() function, and I understand you want it to be more easy to access through GitHub and the Composer Library, me personally love Composer, mad that I didn't knew about it when I build the system. But as a suggestion, back compatibility is always a golden egg.

P.S. Awesome code, loved it till it last for me, is the best one I ever tried.

**Comment by raphievila** [comment]
After I posted the comment I went through a revelation... :grin: ... The theoretical solution is to pass on values required to API that only required the composer `autoload.php`. Can be done through curl request using the CURL PHP object, then returning a JSON with success or fail results. As I said, in theory, this should work, allowing you to use both frameworks, the custom framework and Composer, the best of both worlds.

Create a MVP  file to request specific object for example `cfw.php` (Composer Framework):

```
<?php
require 'vendor/autoload.php';
$error = array();

$post = (object) filter_input(INPUT_POST);

switch($post->method) {
    case 'sendmail-swift':
        $transport = (new Swift_SmtpTransport('smtp.mailgun.org', 587))
                ->setUserName(SMTPUSER)
                ->setPassword(SMTPPASSWORD)
                ->setEncryption('tls');
        $mailer = Swift_Mailer::newInstance($transport);
        $message = Swift_Message::newInstance()
                ->setSubject($post->subject)
                ->setFrom(array($from => $fromTitle))
                ->setSender(array("$post->user" => 'Stealth Mail System'))
                ->setTo(array($post->to => "$name $last"))
                ->setReplyTo(array($post->reply))
                ->setBody($post->text,'text/plain')
                ->addPart($post->html,'text/html')
                ->setContentType('text/pain; charset=UTF-8');

        //processing message to return $jsonArray;
    default:
        $error[] = 'Method do not exists';
}

$errorCount = count($error);

if ($errorCount > 0) {
    echo json_encode($error);
} else {
    echo json_encode($jsonArray);
}

```
Obviously, you need to make sure all the values are passed before executing and the proper Error catching.

Then on the custom framework call this file as a remote file inside any method using [CURL](http://php.net/manual/en/book.curl.php) object:

```
$ch = curl_init(mvp.url);
$post = array(
    'subject' => 'some subject',
    'name' => 'Recipient Name',
    'to' => 'to@exmple.com',
    'fromName' => 'Sender Name',
    'from' => 'from@example.com'
);
$header = array(
    'Method: POST',
    'User-Agent: ' . $userAgent,
    'Content-type: application/x-www-form-urlencoded; charset="UTF-8";',
    'Content-transfer-encoding: UseBase64',
    'Connection: close'
);

if(isset($post) && is_array($post)){
    $posts = array();
    foreach($post as $var=>$val){
                if (is_array($val)) {
                    $posts[] = self::curl_request_array_to_string($var, $val);
                } else {
                    $posts[] = "$var=$val";
                }
      }
      $post_string = (count($posts) > 0)? join("&",$posts) : "";
      $header[] = "Content-length: " . strlen($post_string);
}
curl_setopt($ch, CURLOPT_HTTPHEADER, $header);
curl_setopt($ch, CURLOPT_POST, TRUE);
curl_setopt($ch, CURLOPT_POSTFIELDS, $post_string);

$data = curl_exec($ch);
if($response === FALSE){
    throw new Exception("cURL Error #" . curl_errno($ch) . ": " . curl_error($ch), curl_errno($ch));
}

curl_close($ch);
//Do whatever you want with the data... 
```

As I said... I haven't test this, but should work, in theory.

**Comment by fabpot** [comment]
Not supporting Composer would mean finding a way to include the dependencies. Also, nobody forces the upgrade to the latest version. So, I'm closing as I don't see what we can do here.
