### ISSUE TITLE
Class 'Swift_MailTransport' not found

### ISSUE THREAD

**Issue by Si-Ke-Goe** [swiftmailer/swiftmailer#1092]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/
| Feature request?    | no
| RFC?                | no
| How used?           | Standalone
| Swiftmailer version | 6.1.0
| PHP version         | 5.6.36

### Observed behaviour
The Script dies with the following error:
`Fatal error: Class 'Swift_MailTransport' not found in /php/test_mailer.php on line 5`

**Comment by xabbuh** [comment]
What are the required steps to reproduce the issue that you experience?

**Comment by Si-Ke-Goe** [comment]
I think I found a solution: Composer is not installed on the server, I just manually copied the files from the repository to it.

**Comment by fernandocassola** [comment]
I've installed swiftmailer via composer:
`$ composer require "swiftmailer/swiftmailer:^6.0"`
On my vendor directory i have the directory swiftmailer
but when i try to use swiftmailer to send an email i receive the error:

**Slim Application Error**
The application could not run because of the following error:
Details
Type: Error
Message: Class 'Swift_MailTransport' not found
File: /var/www/html/api-dev/src/routes/backendcron.php
Line: 41

**Comment by fernandocassola** [comment]
I've installed swiftmailer via composer:
$ composer require "swiftmailer/swiftmailer:^6.0"
On my vendor directory i have the directory swiftmailer
but when i try to use swiftmailer to send an email
` // Create Transport
$transport = Swift_MailTransport::newInstance();

// Create Mailer with our Transport.
$mailer = Swift_Mailer::newInstance($transport);

try {

    // Setting all needed info and passing in my email template.
    $message = Swift_Message::newInstance('ECOplay shop')`
(...)

i receive the error on the first line:

Slim Application Error
The application could not run because of the following error:
Details
Type: Error
Message: Class 'Swift_MailTransport' not found
File: /var/www/html/api-dev/src/routes/backendcron.php
Line: 41
