### ISSUE TITLE
Expected response code 220 but got code "", with message ""

### ISSUE THREAD

**Issue by kal11** [swiftmailer/swiftmailer#1109]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | yes/no
| How used?           | Laravel
| Swiftmailer version | Latest (cloned from this repo)
| PHP version         | 7
### Observed behaviour

Tried ssl,tls gmail, zoho, outlook, same result from all.
### Expected behaviour

To send the e-mail
### Example

It's included in the forget password part, and using smtp driver, I click on forgot my password and I am getting the above error, tried to clean the cache and switch between various configs, but it just doesn't work.

**Comment by pavarnos** [comment]
i had many similar errors running a process in daemon mode (under supervisord). Upgrading to 6.1.3 fixed it for me

**Comment by kal11** [comment]
@pavarnos what exactly were you running in daemon mode?

**Comment by pavarnos** [comment]
i have a php background job queue managed by supervisord. One of the (maybe 30 different) tasks is to send daily digest summaries by email. This was failing with similar error messages to yours. The upgrade fixed it (after trying many other things including https://github.com/symfony/swiftmailer-bundle/issues/39).
The problems were caused by changing from a cron job that ran every 5 minutes (where it worked fine for many years) to supervisord (where it didn't).
php 7.2, ubuntu 16.04

**Comment by xdecock** [comment]
The issue is a connection timeout where the server you are connected to
closes the connection.

There is allready dozens of bug like that i'll submit a patch to add
possible timeout in exception if the error code is feof.

Le mer. 25 juil. 2018 à 23:42, Steve Pavarno <notifications@github.com> a
écrit :

**Comment by fabpot** [comment]
@xdecock Will you have time to submit a PR, we indeed have too many issues about the same. Thank you.
