### ISSUE TITLE
stream_socket_client(): unable to connect to

### ISSUE THREAD

**Issue by louia** [swiftmailer/swiftmailer#1190]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/
| Feature request?    | /no
| How used?           | /Symfony 4.2/
| Swiftmailer version | ^3.1
| PHP version         | 7.2.15

### Observed behaviour
`[2019-04-11 20:09:49] php.DEBUG: Warning: stream_socket_client(): unable to connect to ssl://ssl0.ovh.net:465 (Connection refused) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/home/mielleriem/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php\",\"line\":267,\"trace\":[{\"file\":\"/home/mielleriem/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php\",\"line\":58,\"function\":\"establishSocketConnection\",\"class\":\"Swift_Transport_StreamBuffer\",\"type\":\"->\"}],\"count\":1})"} []
[2019-04-11 20:09:49] app.ERROR: Exception occurred while flushing email queue: Connection could not be established with host ssl0.ovh.net [Connection refused #111] [] []
`

my swiftmailer.yaml
`swiftmailer:
    transport: smtp
    host: ssl0.ovh.net
    port: 465
    auth_mode: login
    encryption: ssl
    #auth_mode: login
    username: admin@******.fr
    password: ******
    #intercept_redirects: true
    # disable_delivery: false
    # url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }`

### Expected behaviour
Just send an stupid email

**Comment by xorgxx** [comment]
+1

**Comment by louia** [comment]
Last ver of symfony ? SwiftMailer ? PHP ?

**Comment by xorgxx** [comment]
Sf4.2.5; SwiftMailer last; PHP 7.1.9

**Comment by xorgxx** [comment]
but i think that i have one more probleme : 
```
Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
```
maybe because of this?

**Comment by louia** [comment]
I think, i have not this problem. Your app is runing on shared server ?

**Comment by xorgxx** [comment]
on local server wamp 3.1.8, i have update PHP 7.2.17 and still have this SSL probleme and can't connect to : 

`[2019-04-12 09:34:47] php.DEBUG: Warning: stream_socket_client(): unable to connect to ssl://mail.gandi.net:465 (Unknown error) [] []`

`[2019-04-12 09:47:55] php.DEBUG: Warning: stream_socket_client(): unable to connect to tcp://mail.gandi.net:25 (Une tentative de connexion a �chou� car le parti connect� n�a pas r�pondu convenablement au-del� d�une certaine dur�e ou une connexion �tablie a �chou� car l�h�te de connexion n�a pas r�pondu. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"D:\\\\Programmation\\\\Web\\\\root_www\\\\xxxxxx.ap4\\\\vendor\\\\swiftmailer\\\\swiftmailer\\\\lib\\\\classes\\\\Swift\\\\Transport\\\\StreamBuffer.php\",\"line\":267,\"trace\":[{\"file\":\"D:\\\\Programmation\\\\Web\\\\root_www\\\\neonatis.ap4\\\\vendor\\\\swiftmailer\\\\swiftmailer\\\\lib\\\\classes\\\\Swift\\\\Transport\\\\StreamBuffer.php\",\"line\":58,\"function\":\"establishSocketConnection\",\"class\":\"Swift_Transport_StreamBuffer\",\"type\":\"->\"}],\"count\":1})"} []
`
`[2019-04-12 10:03:34] php.DEBUG: Warning: stream_socket_client(): unable to connect to ssl://mail.gandi.net:993 (Unknown error) [] []
`

i have try all port and stiil the since probleme.

**Comment by xorgxx** [comment]
`[2019-04-14 10:42:45] php.DEBUG: Warning: stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"D:\\\\Programmation\\\\Web\\\\root_www\\\\xxxxx.ap4\\\\vendor\\\\swiftmailer\\\\swiftmailer\\\\lib\\\\classes\\\\Swift\\\\Transport\\\\StreamBuffer.php\",\"line\":267,\"trace\":[{\"file\":\"D:\\\\Programmation\\\\Web\\\\root_www\\\\neonatis.ap4\\\\vendor\\\\swiftmailer\\\\swiftmailer\\\\lib\\\\classes\\\\Swift\\\\Transport\\\\StreamBuffer.php\",\"line\":58,\"function\":\"establishSocketConnection\",\"class\":\"Swift_Transport_StreamBuffer\",\"type\":\"->\"}],\"count\":1})"} []
[2019-04-14 10:42:45] php.DEBUG: Warning: stream_socket_client(): Failed to enable crypto [] []
[2019-04-14 10:42:45] php.DEBUG: Warning: stream_socket_client(): unable to connect to ssl://mail.gandi.net:465 (Unknown error) [] []`

**Comment by xorgxx** [comment]
so in my case i just find the probleme :

in php.ini i have
```
 [curl]
; A default value for the CURLOPT_CAINFO option. This is required to be an
; absolute path.
curl.cainfo = "d:\server\wamp_310_64\ssl\cacert1.pem"
```
and i have to add : 
```
[curl]
; A default value for the CURLOPT_CAINFO option. This is required to be an
; absolute path.
curl.cainfo = "d:\server\wamp_310_64\ssl\cacert1.pem"
```

**Comment by tserofcj** [comment]
@xorgxx in your last comment your php.ini is the same. What did you do to solve your problem?

**Comment by kl3sk** [comment]
@tserofcj apprently a "space" before the ini section
