### ISSUE TITLE
Add Transport that saves to file

### ISSUE THREAD

**Issue by gbirke** [swiftmailer/swiftmailer#186]
For testing purposes and when offline it would be very useful if the Transport could write to a file instead of connecting to some server.

Maybe you can integrate this patch:
http://git.typo3.org/FLOW3/Packages/TYPO3.SwiftMailer.git?a=commit;h=d88f6948f097deb19fd836f6267dc06623266867

**Comment by davidmintz** [comment]
I am looking for the same thing, and I see this request has been around for over 3 years. Is there enough interest in this to warrant trying to implement it ourselves and making a PR? I was actually about to write a  subclass and override send() with something that would do this, so that at bootstrap time your application can look at the environment (development, production) and decide whether to use the real or "fake" mailer.
