### ISSUE TITLE
Plus sign not allowed

### ISSUE THREAD

**Issue by arne-s** [swiftmailer/swiftmailer#250]
When a + sign is present in the local part of an e-mail address, (e.g. my+name@gmail.com) swiftmailer will refuse to send the mail. The + sign should be allowed according to RFC 2822.

**Comment by benwerd** [comment]
Confirming that we still have this problem in Known.

**Comment by xdecock** [comment]
Can you provide a reproduce code with swiftmailer only?

Because, it's been in use in the wild for years.

Then we'll be able to correct this, for now it should be seen as unable to
reproduce. (just tested now with myemail+test@gmail.com without any issue

Regards

Xavier.

On Wed, Sep 2, 2015 at 8:49 PM, Ben Werdmuller <notifications@github.com>
wrote:

> Confirming that we still have this problem in Known.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/250#issuecomment-137207691>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by lucabartoli** [comment]
Didn't check it, but it should be the wrapper class. Symfony and Laravel probably shares the same wrapper for swiftmailer.
Could anyone check it to exclude a SwiftMailer responsibility?

**Comment by xdecock** [comment]
i can send emails by using

->setTo('xxxx+test@gmail.com');



On Thu, Sep 3, 2015 at 1:33 PM, lucabartoli <notifications@github.com>
wrote:

> Didn't check it, but it should be the wrapper class. Symfony and Laravel
> probably shares the same wrapper for swiftmailer.
> Could anyone check it to exclude a SwiftMailer responsibility?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/250#issuecomment-137412923>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by samvaughton** [comment]
I'm currently getting this issue with v5.4.1.

I'm setting the from address in this scenario `noreply+{UUID}@example.com`. 

I get the `Swift_RfcComplianceException`.
