### ISSUE TITLE
Mail created with iso-8859-2 charset is broken

### ISSUE THREAD

**Issue by danielczestki** [swiftmailer/swiftmailer#355]
I creted message encoded with iso-8859-2. I used polish characters.
When I am sending, email message is broken. Polish chars are deleted from message.
When I convert txt message from iso to utf-8 everything is ok.

**Comment by rafalp** [comment]
I'm using latest swift mailer as of the time of writing, and I can confirm that sending e-mails in encodings others than UTF-8 isnt working the way we would want it to.

I can send iso-8859-2 mail no problem as long as two criteria are met:

* charset is set right before sending
* message is not multipart

Even if I set charset right before passing message to transport, if I add extra part to message, message's body conversion fails, producing question marks instead of diacritics, and as bonus points, sometimes just plainly ignoring charset and declaring message utf-8.

**Comment by ntomka** [comment]
I'm faced this issue now and a problem is this: [MimePart.php#L194](https://github.com/swiftmailer/swiftmailer/blob/5.x/lib/classes/Swift/Mime/MimePart.php#L194)
This _convertString method is called in setBody and in line 200 the body is converted to the encoding set earlier from UTF-8 even it is not encoded in UTF-8.

So it would be better to use [mb_detect_encoding()](http://php.net/manual/en/function.mb-detect-encoding.php) instead of hardcoding UTF-8, but it needs a good detect order set as a parameter or [mb_detect_order()](http://php.net/manual/en/function.mb-detect-order.php) must be called earlier with the proper list.

Other solution to convert body string to UTF-8 before setting the email body. I think this is more easier than guess what detect order is suitable for most cases.
