### ISSUE TITLE
Unable to unserialize a broken Swift_Message

### ISSUE THREAD

**Issue by samwilson** [swiftmailer/swiftmailer#426]
(This might just be a "feature" of PHP's serializing, but the fix I have found for it is within Swift Mailer so I'm reporting it here. Feel free to close if I'm off track!)

I am unable to unserialize a truncated serialized Swift_Message. Instead of `unserialize()` returning false and issuing a notice, a fatal error is coming from `SimpleMimeEntity::__destruct()`.

Example:

``` php
// Create and serialise a simple message.
$message = Swift_Message::newInstance()->setBody("body-start xxx bodyend");
$serialized = serialize($message);

// Chop the serialized message off halfway through the body.
$broken = substr($serialized, 0, strpos($serialized, 'xxx'));

// Try to retrieve the original object.
// An E_NOTICE should be issued, but instaead it's a fatal error.
$new = unserialize($broken);
```

The expected notice-error would be something like "Error at offset 6712 of 6727 bytes..." but instead it's "Call to a member function clearAll() on a non-object in \lib\classes\Swift\Mime\SimpleMimeEntity.php on line 834"

Is the following a possible fix for this?

``` php
public function __destruct()
{
    if (method_exists($this->_cache, 'clearAll')) {
        $this->_cache->clearAll($this->_cacheKey);
    }
}
```

Thanks for your time (and for producing a great library!).

**Comment by torinaki** [comment]
Even if you fix issue with fatal error you will never send this email, because of unserialization issues. In case when it is transaction email you will get complain from client. 
I have spend some time to nail this problem, but no luck. Seems it is related to missing object reference in serialized string. I always get following error:
```
Notice: unserialize(): Error at offset 1603 of 27674 bytes
```
That referencing to following part of string:
```
s:59:"Swift_CharacterStream_NgCharacterStream_charReaderFactory";r:264665;
```
Notice points to `r:264665` reference that doesn't exists in whole string.
According to http://www.phpinternalsbook.com/classes_objects/serialization.html I should found something like:
```
"Swift_CharacterReaderFactory":264665:
```
BTW `_charReaderFactory` property must contain `Swift_CharacterReaderFactory` object reference

**Comment by samwilson** [comment]
@torinaki you're quite correct, the broken unserialisable message will never be sent. The point is that `unserialize()` should give an E_NOTICE (reading "Error at offset ..."), rather than a fatal error.

However, if I read your post correctly, you're saying that you're not able to reproduce this issue?
