### ISSUE TITLE
Exception messages from LoadBalancedTransport are too generic

### ISSUE THREAD

**Issue by swiftmailer** [swiftmailer/swiftmailer#49]
The LoadBalancedTransport (and probably the FailoverTransport) should not discard the error messages from the Transports it wraps otherwise debugging becomes difficult.

Original creation date: 2009-02-10T01:57:28Z
Original reporter: Chris Corbyn
Original ticket: http://swiftmailer.lighthouseapp.com/projects/21527/tickets/53

**Comment by nicolasbadia** [comment]
For me this issue is not solved.

LoadBalancedTransport still report a generic issue:

https://github.com/swiftmailer/swiftmailer/blob/a53dab202d27506cad9f0238e8ef2c53dee91c88/lib/classes/Swift/Transport/LoadBalancedTransport.php#L150

It would be great to have the errors from the previous catch block:

https://github.com/swiftmailer/swiftmailer/blob/a53dab202d27506cad9f0238e8ef2c53dee91c88/lib/classes/Swift/Transport/LoadBalancedTransport.php#L143
