### ISSUE TITLE
A message that you sent contained one or more recipient addresses that were incorrectly constructed

### ISSUE THREAD

**Issue by swiftmailer** [swiftmailer/swiftmailer#58]
Send mail fails when recipient name (cyrillic) contains spaces.
See details in attachement.

Original creation date: 2009-04-13T06:19:51Z
Original reporter: Chris Corbyn
Original ticket: http://swiftmailer.lighthouseapp.com/projects/21527/tickets/83

**Comment by stepanselyuk** [comment]
Also possible encode `name` before set to the header:

```php
if (preg_match( '~[\x00-\x08\x10-\x19\x7F-\xFF\r\n]~', $fullname ) && strpos( $fullname, ' ' ) !== false) {
            $fullname = '=?UTF-8?B?' . base64_encode( $fullname ) . '?=';
}
```

**Comment by zlatevbg** [comment]
As a workaround for this bug you can use the PHP's built-in function [mb_encode_mimeheader](http://php.net/manual/en/function.mb-encode-mimeheader.php)

Just encode the **To** name like this:
`$message = Swift_Message::newInstance()->setTo(array('receiver@domain.org' => mb_encode_mimeheader('Тест Тест')));`

It's interesting to note that this bug only happens with the `setTo()` method.
That's why I think this bug has nothing to do with the SwiftMailer at all, but with the specific implementation of the mail servers.

The other methods `setSender()`, `setFrom()`, `setCc()`, `setBcc()`, `setSubject()` accept and encode Cyrillic characters (names or subject lines) with spaces and they all work.

Actually when you pass a name to the `setTo()` method the passed name is encoded in exactly the same way but for some reason the mail is rejected from the mail server and it's not sent.
