### ISSUE TITLE
Swift_Mime_MimePart::_convertString() converts string incorrectly

### ISSUE THREAD

**Issue by koku** [swiftmailer/swiftmailer#644]
We use the iso-8859-15 charset and found that Swift does some incorrect converting in Swift_Mime_MimePart::_convertString().
In this method the mb_convert_encoding() is called with the following parameters:
mb_convert_encoding('Berbée', 'iso-8859-15', 'utf-8');

This results in 'Berb?e'

I'm not sure why the encoding is skipped when utf-8 or iso-8859-1 is used (those charsets aren't the same right?).
It seems it tries to encode the string to the specified charset, but in this case, the given string already is iso-8859-15. Also the $from_encoding param for
mb_convert_encoding shouldn't be utf-8, because it is iso-8859-15. It is strange to assume the source is always utf-8.

Why is '_convertString()' even called in setBody()? Shouldn't you believe that the string is encoded with the given charset?
I hope someone can take a look at this method, because when using a different charset than utf-8 or iso-8859-1, it will cause strings to be encoded incorrectly.

**Comment by sstok** [comment]
The default charset is UTF-8 if you use something else you can set this with setCharset()
http://swiftmailer.org/docs/messages.html#setting-the-character-set

**Comment by koku** [comment]
Of course, we use the setCharset() method, but that doesn't really matter for this bug. On line 9 in the example you gave, an incorrect encoding is still performed (although you wouldn't notice, because the text 'My body' doesn't contain special characters).

**Comment by arjenm** [comment]
To illustrate this issue further, each of these examples displays 'Berb?e' rather than 'Berbée':

Approach 1:
```php
Swift_Preferences::getInstance()->setCharset('iso-8859-2');

$message = Swift_Message::newInstance();

$message->setBody('Berbée');
$text = $message->getBody();
var_dump($text);
```
Approach 2:
```php
$message = Swift_Message::newInstance()->setCharset('iso-8859-2');

$message->setBody('Berbée');
$text = $message->getBody();
var_dump($text);
```
Approach 3:
```php
$message = Swift_Message::newInstance();

$message->setBody('Berbée', null, 'iso-8859-2');
$text = $message->getBody();
var_dump($text);
```

I.e. they convert the body just provided *from* utf-8 *to* iso-8859-2 even though the call itself specified the provided text is supposed to be iso-8859-2.

Perhaps this conversion in _convertString has some use to guarantee a generic string-encoding (but why doesn't it happen for iso-8859-1 or an empty encoding?). In that case the body should be converted the other way around (i.e. into utf-8) and later re-converted back into iso-8859-2. Afaik that later re-conversion doesn't happen and it would be wasteful anyway.

**Comment by everisk** [comment]
I'm also experiencing the same thing
