### ISSUE TITLE
Mail not sent in fosuserbundle with symfony 2.8

### ISSUE THREAD

**Issue by antondachauer** [swiftmailer/swiftmailer#711]
Please visit http://stackoverflow.com/questions/34596190/symfony-swiftmailer-mail-not-sent-in-prod-environment

**Comment by xdecock** [comment]
This is not a swiftmailer bug

Search in your log, this is not the place nor the way to work

**Comment by antondachauer** [comment]
The log is empty. Why are you shure that isn't a swiftmailer bug?

**Comment by xdecock** [comment]
Because, there's no version info, no environment info, no reproduce code
(in php with only plain swiftmailer), as such, i strongly suspect a server
/ middleware configuration issue, you have at least 3 layers before using
swiftmailer.

On Tue, Jan 5, 2016 at 12:53 PM, Anton Dachauer <notifications@github.com>
wrote:

> The log is empty. Why are you shure that isn't a swiftmailer bug?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/711#issuecomment-168980355>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B
