### ISSUE TITLE
Broken attachment

### ISSUE THREAD

**Issue by fredeastside** [swiftmailer/swiftmailer#734]
Hello! I use this code

```
$transport = Swift_MailTransport::newInstance();

// Create the message
$message = Swift_Message::newInstance();
$message->setTo('account@test.com');
$message->setSubject("Normal - image");
$message->setBody("test");
$message->setFrom("test@test.com");
$message->attach(Swift_Attachment::fromPath('about.png'));

// Send the email
$mailer = Swift_Mailer::newInstance($transport);
```

I get the correct letter with correct attachment.

But, when i use this code

```
$transport = Swift_SmtpTransport::newInstance(
    SMTP_SERVER,
    SMTP_PORT
);

// Create the message
$message = Swift_Message::newInstance();
$message->setTo('account@test.com');
$message->setSubject("Not normal - image");
$message->setBody("test");
$message->setFrom("test@test.com");
$message->attach(Swift_Attachment::fromPath('about.png'));

// Send the email
$mailer = Swift_Mailer::newInstance($transport);
```

I get the correct letter with incorrect attachment. 

In the first case image normal, in the second case normally only part of the image. A feeling that part of the image is cut off. Also I noticed that very small image come right. It seems to me that some of the base64 information is erased.

What could happen and how can I debug it?

**Comment by mastervolkov** [comment]
This screenshot shows the difference between these two messages:

![3](https://cloud.githubusercontent.com/assets/2923237/13704499/58f0d136-e7ad-11e5-9ac5-4d7dee312778.png)

Version: Swift-5.4.1

**Comment by Kneggebrot** [comment]
Hey Guys,

any solution for this case?

**Comment by vizh** [comment]
Tried 6.0.1 version and the problem exists.

![2](https://user-images.githubusercontent.com/167476/30782298-cac35d64-a148-11e7-831d-3de2e7cc35cb.jpg)

**Comment by stevenbg** [comment]
I'm having the same issue with my legacy app and I found the possible cause and a solution.
Attaching a file this way leads to corrupted file:
```
$attachment = Swift_Attachment::fromPath($value['path']);
$attachment->setFilename($fname);
$message->attach($attachment);
```
Actually there is some limit where files don't get corrupted (~19kb went okay, ~48kb got garbled).
I didn't get much into it, but apparently Swiftmailer is buffering and using string functions when reading files. String functions which I have overloaded with `mbstring.func_overload = 6`.
That's on PHP 5.4 and Swiftmailer 5.4.9.
Comment above says it also happens in Swiftmailer 6, but mbstring.func_overload is [deprecated in PHP 7.2](http://php.net/manual/en/mbstring.overload.php) and this issue is probably not worth fixing.

Doing it this way works like a charm:
```
$attachment = new Swift_Attachment();
$attachment->setFilename($fname);
$attachment->setBody(file_get_contents($value['path']));
```
