### ISSUE TITLE
BCC and Decorator plugin

### ISSUE THREAD

**Issue by edwh** [swiftmailer/swiftmailer#770]
I'm wanting to use the Decorator plugin to send out mails to a mailing list.  I don't want the members of the mailing list to see the email addresses of other members, but it looks like the Decorator plugin only processes the To recipients.  Shouldn't it process BCC recipients as well?

**Comment by Cipa** [comment]
Anyone has a fix for this?
Thank you

**Comment by daduque** [comment]
I found a solution for this issue, try modify the file `DecoratorPlugin.php` on the path `vendor->swiftmailer->lib->classes->swift->plugins->decorator`

Replace the line `$to = array_keys($message->getTo());` for `$to = array_keys($message->getBcc());`, I changed it cause I only need the Bcc way to send, but if you need both, try with a `if()` cheking if addTo is empty or not.

The error message is because always check first the TO way, if you didn't use it (only use Bcc), the swiftMailer catch that message.

I hope this help.

**Comment by Cipa** [comment]
I did that but did not work entirely for me as only one email was sent. I discovered that the Decorator was not replacing values in the secondary emails and I believe the server was not sending the same email multiple times. 

I ended up doing a foreach loop.
