### ISSUE TITLE
[security] Wrong email address as recipient is included in an error message unescaped

### ISSUE THREAD

**Issue by Cimmo** [swiftmailer/swiftmailer#993]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | 3party
| Swiftmailer version | 6.0.1
| PHP version         | 7.x

### Observed behaviour
\lib\classes\Swift\Mime\Headers\MailboxHeader.php:355
it tries to include unescaped $address in the error message, thus if any user of this library will print the error message as is may suffer of XSS vulnerability since a script can be passed as recipient's address.

### Expected behaviour
Error messages should be safe to be printed.

### Example
Use the library to send an email to
%3Cscript%0D%0A%3Ealert%281%29%3B%3C%2Fscript%0D%0A%3E

**Credit goes to Zach Julian tprime@dsskcorp.com**
I am just reporting on behalf of him.

**Comment by sstok** [comment]
Thanks for reporting, but this is non-issue. It's the developers responsibility to take care of handling exceptions. And proper escaping these when printing (else any library would by definition be vulnerable).

Second, printing a detailed exception message (in production) is a much greater risk (disclosure of sensitive information, paths, application stack (can expose used software), etc). An XSS attack is the least of your worries then.

Always only escape for the context of usage. Or in other words, when your printing information in HTML you escape for HTML, when you use user-provided information in SQL you escape for SQL (_or better use prepared statements/query parameters_ 😸 ). You don't escape HTML for an SQL query, because the information could be used anywhere else (then a web context) later on.
